let weatherData = {
  response:
  { version: '0.1',
    termsofService: 'http://www.wunderground.com/weather/api/d/terms.html',
    features: { conditions: 1 } },
  current_observation:
  { image:
  { url: 'http://icons.wxug.com/graphics/wu2/logo_130x80.png',
    title: 'Weather Underground',
    link: 'http://www.wunderground.com' },
    display_location:
    { full: 'Tecumseh, MI',
      city: 'Tecumseh',
      state: 'MI',
      state_name: 'Michigan',
      country: 'US',
      country_iso3166: 'US',
      zip: '49286',
      magic: '1',
      wmo: '99999',
      latitude: '42.00000000',
      longitude: '-83.94000244',
      elevation: '244.8' },
    observation_location:
    { full: 'Grange Hall Hwy, Tecumseh, Michigan',
      city: 'Grange Hall Hwy, Tecumseh',
      state: 'Michigan',
      country: 'US',
      country_iso3166: 'US',
      latitude: '42.019444',
      longitude: '-83.921272',
      elevation: '872 ft' },
    estimated: {},
    station_id: 'KMITECUM9',
    observation_time: 'Last Updated on November 26, 12:39 AM EST',
    observation_time_rfc822: 'Sun, 26 Nov 2017 00:39:33 -0500',
    observation_epoch: '1511674773',
    local_time_rfc822: 'Sun, 26 Nov 2017 00:40:04 -0500',
    local_epoch: '1511674804',
    local_tz_short: 'EST',
    local_tz_long: 'America/New_York',
    local_tz_offset: '-0500',
    weather: 'Clear',
    temperature_string: '30.7 F (-0.7 C)',
    temp_f: 30.7,
    temp_c: -0.7,
    relative_humidity: '79%',
    wind_string: 'From the NNW at 2.0 MPH',
    wind_dir: 'NNW',
    wind_degrees: 338,
    wind_mph: 2,
    wind_gust_mph: 0,
    wind_kph: 3.2,
    wind_gust_kph: 0,
    pressure_mb: '1020',
    pressure_in: '30.12',
    pressure_trend: '+',
    dewpoint_string: '24 F (-4 C)',
    dewpoint_f: 24,
    dewpoint_c: -4,
    heat_index_string: 'NA',
    heat_index_f: 'NA',
    heat_index_c: 'NA',
    windchill_string: '31 F (-1 C)',
    windchill_f: '31',
    windchill_c: '-1',
    feelslike_string: '31 F (-1 C)',
    feelslike_f: '31',
    feelslike_c: '-1',
    visibility_mi: '10.0',
    visibility_km: '16.1',
    solarradiation: '--',
    UV: '0',
    precip_1hr_string: '0.00 in ( 0 mm)',
    precip_1hr_in: '0.00',
    precip_1hr_metric: ' 0',
    precip_today_string: '0.00 in (0 mm)',
    precip_today_in: '0.00',
    precip_today_metric: '0',
    icon: 'clear',
    icon_url: 'http://icons.wxug.com/i/c/k/nt_clear.gif',
    forecast_url: 'http://www.wunderground.com/US/MI/Tecumseh.html',
    history_url: 'http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMITECUM9',
    ob_url: 'http://www.wunderground.com/cgi-bin/findweather/getForecast?query=42.019444,-83.921272',
    nowcast: '' } }
